# NumPy Temelleri

Bu notebook, NumPy kütüphanesinin temel kavramlarını **satır satır açıklamalı** kod örnekleriyle anlatır.

İçerik:
1. NumPy'a Giriş ve Kurulum
2. Array (Dizi) Oluşturma
3. Array Özellikleri (shape, dtype, ndim)
4. Hazır Array Oluşturma Fonksiyonları
5. İndeksleme ve Dilimleme (Slicing)
6. Array Şekillendirme (Reshape)
7. Matematiksel İşlemler ve Broadcasting
8. Toplulaştırma (Aggregate) Fonksiyonları
9. Rastgele Sayı Üretimi (random modülü)
10. Doğrusal Cebir (Linear Algebra) Temelleri


## 1. NumPy'a Giriş

NumPy (Numerical Python), Python'da bilimsel hesaplama için kullanılan temel kütüphanedir.
Python listelerine göre çok daha hızlı çalışır çünkü veriler bellekte ardışık ve sabit tipte tutulur.

Kullanmadan önce kütüphaneyi projeye dahil etmemiz gerekir.

In [1]:
# numpy kütüphanesini "np" takma adıyla içe aktarıyoruz (bu, topluluk standardıdır)
import numpy as np

# Kurulu olan numpy sürümünü ekrana yazdırıyoruz
print("NumPy sürümü:", np.__version__)

NumPy sürümü: 2.4.4


## 2. Array (Dizi) Oluşturma

NumPy'ın temel veri yapısı `ndarray` (n-boyutlu dizi) adı verilen yapıdır.
Bir Python listesini `np.array()` fonksiyonuna vererek array oluşturabiliriz.

In [2]:
# Basit bir Python listesinden 1 boyutlu (1D) array oluşturuyoruz
liste = [1, 2, 3, 4, 5]        # önce normal bir Python listesi tanımlıyoruz
array_1d = np.array(liste)     # listeyi np.array() ile numpy dizisine çeviriyoruz

print("Array:", array_1d)      # array'in içeriğini yazdırıyoruz
print("Tipi:", type(array_1d)) # değişkenin Python tipini yazdırıyoruz -> numpy.ndarray

Array: [1 2 3 4 5]
Tipi: <class 'numpy.ndarray'>


In [3]:
# İç içe listelerden 2 boyutlu (2D) array, yani matris oluşturuyoruz
matris = np.array([[1, 2, 3],   # birinci satır
                    [4, 5, 6]]) # ikinci satır

print("2D Array:\n", matris)   # matrisi ekrana yazdırıyoruz
print("Boyut sayısı (ndim):", matris.ndim)  # kaç boyutlu olduğunu gösterir -> 2

2D Array:
 [[1 2 3]
 [4 5 6]]
Boyut sayısı (ndim): 2


## 3. Array Özellikleri

Her `ndarray` nesnesi, kendisi hakkında bilgi veren bazı öznitelikler (attribute) barındırır.

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # örnek bir 2x3 boyutunda array oluşturduk

print("shape :", a.shape)   # (satır, sütun) şeklinde boyut bilgisini verir -> (2, 3)
print("ndim  :", a.ndim)    # array'in kaç boyutlu olduğunu verir -> 2
print("size  :", a.size)    # toplam eleman sayısını verir -> 6
print("dtype :", a.dtype)   # elemanların veri tipini verir (int64 gibi)
print("itemsize:", a.itemsize, "byte")  # her bir elemanın bellekte kapladığı byte sayısı

shape : (2, 3)
ndim  : 2
size  : 6
dtype : int64
itemsize: 8 byte


In [5]:
# dtype'ı elle belirterek array oluşturabiliriz
b = np.array([1, 2, 3], dtype=np.float64)  # elemanları ondalıklı (float) sayı olarak tutar

print(b)          # [1. 2. 3.] şeklinde ondalıklı gösterilir
print(b.dtype)    # float64 olduğunu doğrular

[1. 2. 3.]
float64


## 4. Hazır Array Oluşturma Fonksiyonları

NumPy, sık kullanılan array yapılarını tek satırda oluşturmamızı sağlayan hazır fonksiyonlar sunar.

In [6]:
sifirlar = np.zeros((2, 3))   # 2 satır 3 sütunluk, tüm elemanları 0 olan array oluşturur
print("zeros:\n", sifirlar)

birler = np.ones((3, 2))      # 3 satır 2 sütunluk, tüm elemanları 1 olan array oluşturur
print("ones:\n", birler)

birim = np.eye(3)             # 3x3 boyutunda birim (identity) matris oluşturur
print("eye:\n", birim)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# arange: belli aralıkta, belli adımla sayı dizisi oluşturur (Python'daki range'e benzer)
aralik = np.arange(0, 10, 2)   # 0'dan başlar, 10'a kadar (10 dahil değil), 2'şer artar
print("arange:", aralik)       # [0 2 4 6 8]

# linspace: belirtilen aralığı, belirtilen sayıda EŞİT parçaya böler
esit_araliklar = np.linspace(0, 1, 5)  # 0 ile 1 arasında (1 dahil), 5 eşit parçalı sayı üretir
print("linspace:", esit_araliklar)     # [0.   0.25 0.5  0.75 1.  ]

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


## 5. İndeksleme ve Dilimleme (Slicing)

Array elemanlarına, Python listelerine benzer şekilde köşeli parantez `[]` ile erişilir.
Çok boyutlu array'lerde eksenler virgülle ayrılarak indekslenir.

In [8]:
a = np.array([10, 20, 30, 40, 50])  # 1D array oluşturduk

print(a[0])      # ilk elemanı seçer -> 10 (indeksler 0'dan başlar)
print(a[-1])     # son elemanı seçer -> 50 (negatif indeks sondan sayar)
print(a[1:4])    # 1. indeksten 4. indekse KADAR (4 hariç) dilimler -> [20 30 40]
print(a[:3])     # baştan 3. indekse kadar dilimler -> [10 20 30]
print(a[::2])    # baştan sona, 2'şer adımla ilerler -> [10 30 50]

10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [9]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])   # 3x3 boyutunda örnek matris

print(m[1, 2])     # 1. satır, 2. sütundaki elemanı seçer -> 6
print(m[0])        # 0. satırın tamamını seçer -> [1 2 3]
print(m[:, 1])      # tüm satırların 1. sütununu seçer -> [2 5 8]
print(m[0:2, 0:2])  # ilk 2 satır ve ilk 2 sütunu içeren alt matrisi seçer

6
[1 2 3]
[2 5 8]
[[1 2]
 [4 5]]


In [10]:
# Boolean (mantıksal) indeksleme: koşula uyan elemanları seçmemizi sağlar
a = np.array([1, 2, 3, 4, 5, 6])

kosul = a > 3          # her eleman için 3'ten büyük mü diye True/False dizisi üretir
print("Koşul dizisi:", kosul)      # [False False False  True  True  True]

print("Filtrelenmiş:", a[kosul])   # sadece True olan konumlardaki elemanları getirir -> [4 5 6]
# Aynı işlemi tek satırda da yazabiliriz:
print(a[a % 2 == 0])   # a içindeki çift sayıları doğrudan filtreler -> [2 4 6]

Koşul dizisi: [False False False  True  True  True]
Filtrelenmiş: [4 5 6]
[2 4 6]


## 6. Array Şekillendirme (Reshape)

`reshape()` fonksiyonu, bir array'in eleman sayısını değiştirmeden boyutlarını (satır/sütun) yeniden düzenler.

In [11]:
a = np.arange(12)          # 0'dan 11'e kadar 12 elemanlı 1D array oluşturur
print("Orijinal:", a)

b = a.reshape(3, 4)         # 12 elemanı 3 satır 4 sütun olacak şekilde yeniden şekillendirir
print("3x4 şekline dönüştürülmüş:\n", b)

c = a.reshape(2, 2, 3)      # aynı elemanları 2x2x3 boyutunda 3 boyutlu array yapar
print("2x2x3 şekline dönüştürülmüş:\n", c)

d = b.flatten()             # çok boyutlu array'i tekrar tek boyuta (1D) düzleştirir
print("Düzleştirilmiş:", d)

Orijinal: [ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 şekline dönüştürülmüş:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2x2x3 şekline dönüştürülmüş:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
Düzleştirilmiş: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 7. Matematiksel İşlemler ve Broadcasting

NumPy'da matematiksel işlemler eleman bazında (element-wise) yapılır, yani döngü yazmaya gerek kalmaz.
Farklı boyuttaki array'ler arasında işlem yapılabilmesini sağlayan mekanizmaya **broadcasting** denir.

In [12]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("Toplama   :", a + b)   # elemanları karşılıklı olarak toplar -> [11 22 33]
print("Çıkarma   :", b - a)   # elemanları karşılıklı olarak çıkarır -> [9 18 27]
print("Çarpma    :", a * b)   # elemanları karşılıklı olarak çarpar (matris çarpımı DEĞİL) -> [10 40 90]
print("Bölme     :", b / a)   # elemanları karşılıklı olarak böler -> [10. 10. 10.]
print("Üs alma   :", a ** 2)  # her elemanın karesini alır -> [1 4 9]

Toplama   : [11 22 33]
Çıkarma   : [ 9 18 27]
Çarpma    : [10 40 90]
Bölme     : [10. 10. 10.]
Üs alma   : [1 4 9]


In [13]:
# Broadcasting örneği: farklı boyuttaki array'ler otomatik olarak uyumlu hale getirilir
matris = np.array([[1, 2, 3],
                    [4, 5, 6]])   # 2x3 boyutunda matris
vektor = np.array([10, 20, 30])  # 1x3 boyutunda vektör

sonuc = matris + vektor  # numpy, vektörü her satıra otomatik olarak "yayarak" (broadcast) toplar
print(sonuc)
# Sonuç:
# [[11 22 33]
#  [14 25 36]]

[[11 22 33]
 [14 25 36]]


In [14]:
# Skaler (tek sayı) ile array arasında işlem de broadcasting'in en basit halidir
a = np.array([1, 2, 3, 4])

print(a + 5)    # her elemana 5 ekler -> [6 7 8 9]
print(a * 2)    # her elemanı 2 ile çarpar -> [2 4 6 8]

[6 7 8 9]
[2 4 6 8]


## 8. Toplulaştırma (Aggregate) Fonksiyonları

NumPy, bir array üzerindeki istatistiksel özetleri (toplam, ortalama, min, max vb.) hesaplayan hazır fonksiyonlar sunar.

In [15]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Toplam       :", a.sum())         # tüm elemanların toplamı -> 21
print("Ortalama     :", a.mean())        # tüm elemanların aritmetik ortalaması -> 3.5
print("Standart sapma:", a.std())        # standart sapma değeri
print("Minimum      :", a.min())         # en küçük eleman -> 1
print("Maksimum     :", a.max())         # en büyük eleman -> 6

# axis parametresi ile işlemi satır ya da sütun bazında yapabiliriz
print("Sütun toplamları (axis=0):", a.sum(axis=0))  # her sütunu kendi içinde toplar -> [5 7 9]
print("Satır toplamları (axis=1):", a.sum(axis=1))  # her satırı kendi içinde toplar -> [6 15]

Toplam       : 21
Ortalama     : 3.5
Standart sapma: 1.707825127659933
Minimum      : 1
Maksimum     : 6
Sütun toplamları (axis=0): [5 7 9]
Satır toplamları (axis=1): [ 6 15]


## 9. Rastgele Sayı Üretimi (random modülü)

`np.random` modülü, rastgele sayı ve array üretmek için kullanılır. Bilimsel tekrarlanabilirlik için `seed` sabitlenebilir.

In [16]:
np.random.seed(42)   # rastgelelik "tohum"unu sabitliyoruz; böylece her çalıştırmada aynı sonuçlar üretilir

rastgele_array = np.random.rand(3, 3)      # 0 ile 1 arasında, 3x3 boyutunda rastgele ondalıklı sayılar üretir
print("rand:\n", rastgele_array)

tam_sayilar = np.random.randint(1, 100, size=5)  # 1 (dahil) ile 100 (hariç) arasında 5 rastgele tam sayı üretir
print("randint:", tam_sayilar)

normal_dagilim = np.random.randn(4)   # standart normal dağılımdan (ortalama 0, std 1) 4 sayı üretir
print("randn:", normal_dagilim)

rand:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
randint: [24  3 22 53  2]
randn: [0.23309524 0.11799461 1.46237812 1.53871497]


## 10. Doğrusal Cebir (Linear Algebra) Temelleri

NumPy'ın `linalg` alt modülü, matris çarpımı, determinant, ters matris gibi doğrusal cebir işlemlerini sağlar.

In [17]:
A = np.array([[1, 2],
              [3, 4]])   # 2x2 boyutunda örnek matris

B = np.array([[5, 6],
              [7, 8]])   # ikinci 2x2 matris

# Matris çarpımı: eleman bazlı çarpımdan farklıdır, "@" operatörü veya np.dot() ile yapılır
carpim = A @ B                 # matris çarpımını gerçekleştirir
print("Matris çarpımı:\n", carpim)

determinant = np.linalg.det(A)  # A matrisinin determinantını hesaplar
print("Determinant:", determinant)

ters_matris = np.linalg.inv(A)  # A matrisinin tersini (inverse) hesaplar
print("Ters matris:\n", ters_matris)

transpoze = A.T                 # satır ve sütunları yer değiştirir (transpoze alır)
print("Transpoze:\n", transpoze)

Matris çarpımı:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Ters matris:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Transpoze:
 [[1 3]
 [2 4]]


## Özet

Bu notebook'ta öğrendiklerimiz:

- Array oluşturma (`np.array`, `zeros`, `ones`, `eye`, `arange`, `linspace`)
- Array özellikleri (`shape`, `ndim`, `size`, `dtype`)
- İndeksleme, dilimleme ve boolean filtreleme
- `reshape` ile boyut değiştirme
- Eleman bazlı matematiksel işlemler ve **broadcasting**
- Toplulaştırma fonksiyonları (`sum`, `mean`, `std`, `min`, `max`)
- `np.random` ile rastgele sayı üretimi
- `np.linalg` ile temel doğrusal cebir işlemleri

Daha fazlası için resmi dokümantasyon: https://numpy.org/doc/
